### ISSUE TITLE
Invisible with Lucky Blocks

### ISSUE THREAD

**Issue by WenXin20** [Epoxide-MC/Colorful-Mobs#1]
With lucky blocks, it spawns mobs in invisible

**Comment by Darkhax** [comment]
Can you please provide some more information, along with steps to reproduce?

**Comment by WenXin20** [comment]
When I break a Lucky block, if it summons a mob, it is invisible. If I get an the mob, the color wand tells me the colors are set to 0 0 0, with invisibility at 100%.

**Comment by Darkhax** [comment]
Unfortunately I can not verify this as I can not obtain a copy of the Lucky Blocks mod. The only download available is the official one posted on minecraft-downloads.com however that site is notorious for hosting malware, and google blocked my attempt to access the download page. While I am all for supporting compatibility for other mods, I have to draw the line somewhere. I am going to assume this issue is a duplicate of your other issue, and close this issue. If that assumption is wrong, then I guess this will be the end of the road.
